# This file is part of FAST-OAD_CS23-HE : A framework for rapid Overall Aircraft Design of Hybrid
# Electric Aircraft.
# Copyright (C) 2025 ISAE-SUPAERO

import numpy as np
import openmdao.api as om

from ..constants import (
    FARADAY_CONSTANT,
    H2_MOL_PER_KG,
    NUMBER_OF_ELETRONS_FROM_H2,
    DEFAULT_HYDROGEN_CONSUMPTION,
)


class PerformancesPEMFCStackBOPAirInletOutletDrag(om.ExplicitComponent):
    """
    Computation of the drag generated by the air inlet and outlet for the PEMFC oxidation reaction.
    """

    def initialize(self):
        self.options.declare(
            name="pemfc_stack_bop_id",
            default=None,
            desc="Identifier of the PEMFC stack",
            allow_none=False,
        )
        self.options.declare(
            "number_of_points", default=1, desc="number of equilibrium to be treated"
        )
        self.options.declare(
            name="drag_component_ids",
            default="None",
            desc="A list of the TBS components that create drag",
            allow_none=False,
        )

    def setup(self):
        number_of_points = self.options["number_of_points"]
        pemfc_stack_bop_id = self.options["pemfc_stack_bop_id"]
        drag_component_ids = self.options["drag_component_ids"]

        for drag_component_id in drag_component_ids:
            self.add_input(
                name="data:propulsion:he_power_train:PEMFC_stack_bop:"
                + pemfc_stack_bop_id
                + ":"
                + drag_component_id
                + ":drag",
                units="N",
                val=np.nan,
                shape=number_of_points,
            )

        self.add_output(
            "air_inlet_outlet_drag",
            units="N",
            val=0.1,
            shape=number_of_points,
        )

    def setup_partials(self):
        number_of_points = self.options["number_of_points"]

        self.declare_partials(
            of="air_inlet_outlet_drag",
            wrt="*",
            method="exact",
            rows=np.arange(number_of_points),
            cols=np.arange(number_of_points),
            val=1.0,
        )

    def compute(self, inputs, outputs, discrete_inputs=None, discrete_outputs=None):
        number_of_points = self.options["number_of_points"]
        pemfc_stack_bop_id = self.options["pemfc_stack_bop_id"]
        drag_component_ids = self.options["drag_component_ids"]

        drag = np.zeros(number_of_points)

        for drag_component_id in drag_component_ids:
            drag = (
                drag
                + inputs[
                    "data:propulsion:he_power_train:PEMFC_stack_bop:"
                    + pemfc_stack_bop_id
                    + ":"
                    + drag_component_id
                    + ":drag"
                ]
            )

        outputs["air_inlet_outlet_drag"] = drag
