# This file is part of FAST-OAD_CS23-HE : A framework for rapid Overall Aircraft Design of Hybrid
# Electric Aircraft.
# Copyright (C) 2025 ISAE-SUPAERO

ELECTRIC_ATR_42_VARIABLE_INITIALIZATION = [
    "data:geometry:wing:MAC:at25percent:x",
    "data:geometry:wing:area",
    "data:geometry:horizontal_tail:area",
    "data:geometry:vertical_tail:area",
    "data:weight:aircraft:MTOW",
    "data:weight:aircraft:OWE",
    "data:weight:aircraft:MZFW",
    "data:weight:aircraft:MLW",
    "data:weight:aircraft_empty:mass",
    "data:weight:aircraft_empty:CG:x",
    "data:weight:airframe:wing:mass",
    "data:weight:airframe:fuselage:mass",
    "data:weight:airframe:horizontal_tail:mass",
    "data:weight:airframe:vertical_tail:mass",
    "data:weight:airframe:landing_gear:main:mass",
    "data:weight:airframe:landing_gear:front:mass",
    "data:propulsion:he_power_train:mass",
    "data:propulsion:he_power_train:battery_pack:battery_pack_1:cell:c_rate_caliber",
    "data:propulsion:he_power_train:battery_pack:battery_pack_2:cell:c_rate_caliber",
    "data:weight:systems:auxiliary_power_unit:mass",
    "data:weight:systems:electric_systems:electric_generation:mass",
    "data:weight:systems:electric_systems:electric_common_installation:mass",
    "data:weight:systems:hydraulic_systems:mass",
    "data:weight:systems:fire_protection:mass",
    "data:weight:systems:flight_furnishing:mass",
    "data:weight:systems:automatic_flight_system:mass",
    "data:weight:systems:communications:mass",
    "data:weight:systems:ECS:mass",
    "data:weight:systems:de-icing:mass",
    "data:weight:systems:navigation:mass",
    "data:weight:systems:flight_controls:mass",
    "data:weight:furniture:furnishing:mass",
    "data:weight:furniture:water:mass",
    "data:weight:furniture:interior_integration:mass",
    "data:weight:furniture:insulation:mass",
    "data:weight:furniture:cabin_lighting:mass",
    "data:weight:furniture:seats_crew_accommodation:mass",
    "data:weight:furniture:oxygen:mass",
    "data:weight:operational:items:passenger_seats:mass",
    "data:weight:operational:items:unusable_fuel:mass",
    "data:weight:operational:items:documents_toolkit:mass",
    "data:weight:operational:items:galley_structure:mass",
    "data:weight:operational:equipment:others:mass",
]
