# This file is part of FAST-OAD_CS23-HE : A framework for rapid Overall Aircraft Design of Hybrid
# Electric Aircraft.
# Copyright (C) 2026 ISAE-SUPAERO

POSSIBLE_POSITIONS = {
    "DC_bus": ["inside_the_wing", "in_the_front", "in_the_back"],
    "DC_cable_harness": [],
    "DC_SSPC": ["inside_the_wing", "in_the_front", "in_the_back"],
    "DC_splitter": ["inside_the_wing", "in_the_front", "in_the_back"],
    "rectifier": ["inside_the_wing", "in_the_front", "in_the_back"],
    "DC_DC_converter": ["inside_the_wing", "in_the_front", "in_the_back"],
    "inverter": ["inside_the_wing", "in_the_front", "in_the_back"],
    "speed_reducer": ["inside_the_wing", "in_the_front", "in_the_back"],
    "planetary_gear": ["inside_the_wing", "in_the_front", "in_the_back"],
    "gearbox": ["inside_the_wing", "in_the_front", "in_the_back"],
    "PMSM": ["on_the_wing", "in_the_nose"],
    "SM_PMSM": ["on_the_wing", "in_the_nose"],
    "aux_load": ["inside_the_wing", "in_the_front", "in_the_back"],
    "battery_pack": ["inside_the_wing", "wing_pod", "in_the_front", "in_the_back", "underbelly"],
    "generator": ["inside_the_wing", "in_the_front", "in_the_back"],
    "turbo_generator": ["inside_the_wing", "in_the_front", "in_the_back"],
    "ICE": ["on_the_wing", "in_the_front", "in_the_back"],
    "high_rpm_ICE": ["on_the_wing", "in_the_front", "in_the_back"],
    "turboshaft": ["on_the_wing", "in_the_front", "in_the_back"],
    "PEMFC_stack": ["in_the_front", "wing_pod", "underbelly", "in_the_back"],
    "propeller": ["on_the_wing", "in_the_nose"],
    "fuel_tank": ["inside_the_wing", "wing_pod", "in_the_fuselage"],
    "gaseous_hydrogen_tank": ["in_the_cabin", "wing_pod", "in_the_back", "underbelly"],
    "fuel_system": ["in_the_wing", "in_the_front", "in_the_back"],
    "H2_fuel_system": ["in_the_front", "in_the_middle", "in_the_rear"],
}

POSSIBLE_COMPONENT_TYPES = {
    "bus_bar": "DC_bus",
    "cable": "DC_cable_harness",
    "switch": "DC_SSPC",
    "splitter": "DC_splitter",
    "rectifier": "rectifier",
    "dc_converter": "DC_DC_converter",
    "inverter": "inverter",
    "gearbox": ["speed_reducer", "planetary_gear", "gearbox"],
    "e_motor": ["PMSM", "SM_PMSM"],
    "dc_load": "aux_load",
    "battery": "battery_pack",
    "generator": ["generator", "turbo_generator"],
    "ice": ["ICE", "high_rpm_ICE"],
    "turbine": "turboshaft",
    "fuel_cell": "PEMFC_stack",
    "propeller": "propeller",
    "fuel_tank": ["fuel_tank", "gaseous_hydrogen_tank"],
    "fuel_system": ["fuel_system", "H2_fuel_system"],
}

# number_of_points_reserve
POSSIBLE_OPTIONS = {
    "DC_bus": {},
    "DC_cable_harness": {},
    "DC_SSPC": {"closed": [True, False], "at_bus_output": [True, False]},
    "DC_splitter": {"splitter_mode": ["percent_split", "power_share"]},
    "rectifier": {},
    "DC_DC_converter": {},
    "inverter": {},
    "speed_reducer": {},
    "planetary_gear": {"gear_mode": ["percent_split", "power_share"]},
    "gearbox": {},
    "PMSM": {},
    "SM_PMSM": {},
    "aux_load": {},
    "battery_pack": {"direct_bus_connection": [False, True]},
    "generator": {},
    "turbo_generator": {},
    "ICE": {},
    "high_rpm_ICE": {},
    "turboshaft": {"adjust_sfc": [True, False]},
    "PEMFC_stack": {
        "model_fidelity": ["empirical", "analytical"],
        "direct_bus_connection": [False, True],
        "compressor_connection": [False, True],
    },
    "propeller": {},
    "fuel_tank": {},
    "gaseous_hydrogen_tank": {},
    "fuel_system": {},
    "H2_fuel_system": {},
}

DEFAULT_SOURCE_COUNT = {
    "DC_bus": 3,
    "DC_cable_harness": 1,
    "DC_SSPC": 1,
    "DC_splitter": 2,
    "rectifier": 1,
    "DC_DC_converter": 1,
    "inverter": 1,
    "speed_reducer": 1,
    "planetary_gear": 2,
    "gearbox": 1,
    "PMSM": 1,
    "SM_PMSM": 1,
    "aux_load": 1,
    "battery_pack": 0,
    "generator": 1,
    "turbo_generator": 1,
    "ICE": 1,
    "high_rpm_ICE": 1,
    "turboshaft": 1,
    "PEMFC_stack": 1,
    "propeller": 1,
    "fuel_tank": 0,
    "gaseous_hydrogen_tank": 0,
    "fuel_system": 3,
    "H2_fuel_system": 3,
}

DEFAULT_TARGET_COUNT = {
    "DC_bus": 3,
    "DC_cable_harness": 1,
    "DC_SSPC": 1,
    "DC_splitter": 1,
    "rectifier": 1,
    "DC_DC_converter": 1,
    "inverter": 1,
    "speed_reducer": 1,
    "planetary_gear": 1,
    "gearbox": 2,
    "PMSM": 1,
    "SM_PMSM": 1,
    "aux_load": 0,
    "battery_pack": 1,
    "generator": 1,
    "turbo_generator": 1,
    "ICE": 1,
    "high_rpm_ICE": 1,
    "turboshaft": 1,
    "PEMFC_stack": 1,
    "propeller": 0,
    "fuel_tank": 1,
    "gaseous_hydrogen_tank": 1,
    "fuel_system": 3,
    "H2_fuel_system": 3,
}

# Dict of component_type -> list of options that can have multiple instances (e.g. "fuel_system"
# -> [source, target])
MULTI_PORT_OPTIONS = {
    "DC_bus": ["number_of_inputs", "number_of_outputs"],
    "fuel_system": ["number_of_tanks", "number_of_engines"],
    "H2_fuel_system": ["number_of_tanks", "number_of_power_sources"],
}
